import type { NormalizedResearchSource, ResearchCompanyIdentity, ResearchAcquisitionDiagnostic, ResearchProviderOutcome } from '../../plugins/research-acquisition/contracts.ts'
import type { SemanticProductionProposal } from '../../knowledge/production/contracts.ts'

export type SemanticKnowledgeProposal = SemanticProductionProposal

export interface CompanyResearchFinancialObservation { readonly periodEnd?: string; readonly publishedAt?: string; readonly metrics: Readonly<{ revenue?: number; netProfit?: number; grossMargin?: number; basicEps?: number; metric?: number }>; readonly pointInTimeSafe: boolean }
export interface CompanyResearchMarketObservation { readonly observedAt: string; readonly open?: number; readonly high?: number; readonly low?: number; readonly close?: number; readonly volume?: number; readonly pointInTimeSafe: false }
export interface CompanyResearchProfileData { readonly fields: readonly { readonly name: string; readonly value: string | number | boolean }[] }
export interface CompanyResearchInput { readonly company: ResearchCompanyIdentity; readonly asOf: string; readonly sources: readonly NormalizedResearchSource[]; readonly profileData?: CompanyResearchProfileData; readonly financialData?: readonly CompanyResearchFinancialObservation[]; readonly marketData?: readonly CompanyResearchMarketObservation[]; readonly existingKnowledgeProjection?: unknown }
export interface CompanyResearchResult { readonly company: ResearchCompanyIdentity; readonly generatedAt: string; readonly asOf: string; readonly sections: readonly { readonly id: string; readonly title: string; readonly markdown: string; readonly sourceCandidateIds: readonly string[]; readonly proposalIds: readonly string[] }[]; readonly proposals: readonly SemanticKnowledgeProposal[]; readonly sourceCandidateIds: readonly string[]; readonly valuation?: unknown; readonly acquisitionDiagnostics?: readonly ResearchAcquisitionDiagnostic[]; readonly providerOutcomes?: readonly ResearchProviderOutcome[] }
