import { createHash } from 'node:crypto'
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { tmpdir } from 'node:os'
import assert from 'node:assert/strict'
import test from 'node:test'
import { KnowledgeBaseLoader, KnowledgeBaseRegistry, KnowledgeIndexV03, deriveRawIdentity } from '../../../packages/shared/knowledge-base/index.ts'
import { KnowledgeCurationSkill, type KnowledgeCurationModel, type KnowledgeCurationModelRequest } from '../../../packages/skills/knowledge-curation/index.ts'
import { ResearchReportKnowledgeIngestionWorkflow, researchReportKnowledgeIngestionWorkflowDefinition } from '../../../packages/workflows/research-report-knowledge-ingestion/index.ts'
import { createRuntimeKnowledgeBase, removeRuntimeKnowledgeBase } from '../runtime/helpers.ts'

async function put(root: string, path: string, value: unknown): Promise<void> { const file = join(root, path); await mkdir(dirname(file), { recursive: true }); await writeFile(file, `${JSON.stringify(value)}\n`, 'utf8') }
async function createV03Root(status: 'active' | 'readonly' = 'active'): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), 'researchhub-ingestion-v03-'))
  await put(root, 'manifest.yaml', { knowledgeBaseId: 'kb-runtime-test', name: 'Workflow Fixture', schemaVersion: '0.3', storageFormatVersion: '1', revision: 0, status, createdAt: '2026-08-26T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' })
  await put(root, 'entities/company.yaml', { id: 'entity:existing', type: 'company', name: 'Example Company', aliases: ['Example'], lifecycle: { status: 'active' } })
  await put(root, 'entities/industry.yaml', { id: 'entity:semiconductor', type: 'industry', name: 'Semiconductor', lifecycle: { status: 'active' } })
  await put(root, 'registry/assets.yaml', { 'entity:existing': { type: 'entity', storageRef: 'entities/company.yaml' }, 'entity:semiconductor': { type: 'entity', storageRef: 'entities/industry.yaml' } })
  await put(root, 'registry/raw.yaml', {})
  return root
}
async function target(root: string) { const loader = new KnowledgeBaseLoader({ registry: new KnowledgeBaseRegistry() }); const handle = await loader.mount(root); const state = await loader.loadRuntimeState(handle); assert.ok(state.index instanceof KnowledgeIndexV03); return { handle, index: state.index } }
function input(mode: 'commit' | 'dry_run', text = 'Example Company operates in semiconductors and revenue increased.', metadata: Partial<{ title: string | null; publisher: string | null; institution: string | null; author: string | null; publishedAt: string | null; sourceUrl: string | null }> = {}): { workflowRunId: string; knowledgeBaseId: string; report: { inputRef: { type: 'text'; text: string }; suppliedMetadata: { title: string | null; publisher: string | null; institution: string | null; author: string | null; publishedAt: string | null; sourceUrl: string | null } }; options: { mode: 'commit' | 'dry_run'; reprocess: boolean } } { return { workflowRunId: `run-${mode}`, knowledgeBaseId: 'kb-runtime-test', report: { inputRef: { type: 'text', text }, suppliedMetadata: { title: 'Workflow Report', publisher: 'Research House', institution: null, author: 'Analyst', publishedAt: '2026-08-26', sourceUrl: 'https://example.test/report', ...metadata } }, options: { mode, reprocess: false } } }
function understanding() { return { sourceAssessment: { sourceType: 'professional_media', publisher: 'Research House', institution: null, author: 'Analyst', publishedAt: '2026-08-26', primaryOrSecondary: 'secondary', sourceReliability: 'medium', sourceIdentityConfidence: 0.9, reasoning: ['Metadata is consistent.'] }, researchScope: ['semiconductor'], majorTopics: ['revenue'], majorEntityMentions: [{ mention: 'Example Company', entityType: 'company', suggestedExistingRef: 'entity:existing', evidenceChunkRefs: ['chunk-0001'], reason: 'Named in report.' }], themeHypotheses: [], uncertainty: [] } }
function extraction() { return { entities: [{ entityType: 'company', name: 'New Company', aliases: [], description: null, suggestedExistingRef: null, semanticFields: {}, evidenceChunkRefs: ['chunk-0001'], reason: 'Named as a company.' }], relations: [{ relationType: 'business_exposure', sourceMention: { text: 'Example Company', entityType: 'company', existingRef: 'entity:existing' }, targetMention: { text: 'Semiconductor', entityType: 'industry', existingRef: 'entity:semiconductor' }, attributes: { exposureBasis: 'direct_operation', realizationStage: 'reported', materiality: 'material' }, contextMentions: [], evidenceChunkRefs: ['chunk-0001'], reason: 'Describes business exposure.' }], claims: [{ claimType: 'fact', statement: 'Example Company revenue increased.', subjectMentions: [{ text: 'Example Company', entityType: 'company', existingRef: 'entity:existing' }], temporal: null, structuredValue: { metric: 'growth', value: 0.2, unit: 'ratio', comparator: 'approx' }, semanticConfidence: 0.85, evidenceChunkRefs: ['chunk-0001'], reason: 'Direct report statement.' }] } }
class WorkflowModel implements KnowledgeCurationModel {
  readonly requests: KnowledgeCurationModelRequest[] = []
  async invoke(request: KnowledgeCurationModelRequest): Promise<unknown> { this.requests.push(request); if (request.operation === 'understandReport') return understanding(); if (request.operation === 'extractKnowledge') return extraction(); if (request.operation === 'reconcileKnowledge') { const groups = (request.input as { groups: Array<{ candidates: Array<{ candidateId: string }> }> }).groups; return { decisions: groups.flatMap((group) => group.candidates.map((candidate) => ({ candidateId: candidate.candidateId, decision: 'create', classification: 'complementary', existingRefs: [], reason: 'No duplicate in precise context.', requiresUserReview: false }))) } } return { gaps: [] } }
}
function modelSkill(model = new WorkflowModel()) { return { model, skill: new KnowledgeCurationSkill({ model }) } }
function workflow(root: string, model = new WorkflowModel(), extra: Record<string, unknown> = {}) { return new ResearchReportKnowledgeIngestionWorkflow({ targetResolver: { resolve: async () => target(root) }, curation: new KnowledgeCurationSkill({ model }), ...extra }) }

test('workflow definition is the frozen eighteen-stage v0.3 sequence', () => { assert.equal(researchReportKnowledgeIngestionWorkflowDefinition.version, '0.3'); assert.equal(researchReportKnowledgeIngestionWorkflowDefinition.steps.length, 18); assert.equal(researchReportKnowledgeIngestionWorkflowDefinition.steps[0]?.id, 'intake-execution-identity'); assert.equal(researchReportKnowledgeIngestionWorkflowDefinition.steps[17]?.id, 'final-result-log-refresh'); assert.equal(researchReportKnowledgeIngestionWorkflowDefinition.steps[6]?.skill, 'knowledge-access'); assert.equal(researchReportKnowledgeIngestionWorkflowDefinition.steps[11]?.skill, 'knowledge-access') })

test('accepts only native Schema 0.3 / Storage 1 and rejects a Schema 0.2 commit', async () => { const root = await createRuntimeKnowledgeBase(); try { const legacyLoader = new KnowledgeBaseLoader({ registry: new KnowledgeBaseRegistry() }); const result = await new ResearchReportKnowledgeIngestionWorkflow({ targetResolver: { resolve: async () => ({ handle: await legacyLoader.mount(root), index: {} as KnowledgeIndexV03 }) }, curation: new KnowledgeCurationSkill({ model: new WorkflowModel() }) }).execute(input('commit')); assert.equal(result.status, 'blocked'); assert.equal(result.errors[0]?.code, 'unsupported_schema'); assert.match(result.errors[0]?.message ?? '', /0\.3/) } finally { await removeRuntimeKnowledgeBase(root) } })
test('requires an active writable target for commit but permits readable readonly dry-run', async () => { const root = await createV03Root('readonly'); try { const commit = await workflow(root).execute(input('commit')); assert.equal(commit.status, 'blocked'); assert.equal(commit.errors[0]?.code, 'target_not_writable'); const dry = await workflow(root).execute(input('dry_run')); assert.notEqual(dry.status, 'blocked'); assert.equal(dry.raw.persisted, false); assert.equal(dry.validation?.status, 'passed'); assert.equal(dry.finalRevision, 0) } finally { await removeRuntimeKnowledgeBase(root) } })
test('commit archives Raw first, creates deterministic Source/Entity/Relation/Claim atomically, and reloads native v0.3 state', async () => { const root = await createV03Root(); try { const model = new WorkflowModel(); const result = await workflow(root, model).execute(input('commit')); assert.equal(result.status, 'completed', JSON.stringify(result.errors)); assert.equal(result.raw.persisted, true); assert.equal(result.raw.created, true); assert.equal(result.source?.resolution, 'source_create'); assert.equal(result.plannedChanges.knowledgeCreate.length, 3); assert.equal(result.committedChanges.knowledgeCreated, 3); assert.equal(result.finalRevision, 1); assert.equal(model.requests.filter((request) => request.operation === 'understandReport').length, 1); assert.equal(model.requests.filter((request) => request.operation === 'extractKnowledge').length, result.batches.batchCount); assert.ok(model.requests.some((request) => request.operation === 'reconcileKnowledge')); const reloaded = await target(root); assert.equal(reloaded.index.entities.size, 3); assert.equal(reloaded.index.relations.size, 1); assert.equal(reloaded.index.claims.size, 1); assert.equal((await new (await import('../../../packages/skills/knowledge-validation/index.ts')).KnowledgeValidationSkill({ loader: new KnowledgeBaseLoader() }).validateKnowledgeBase(reloaded.handle)).status, 'passed'); const log = await readFile(join(root, 'logs/ingestion/run-commit.yaml'), 'utf8'); assert.match(log, /completed/) } finally { await removeRuntimeKnowledgeBase(root) } })
test('dry-run reaches final validation without Raw, Source, receipt, Writer, or mutation', async () => { const root = await createV03Root('readonly'); try { let writes = 0; const before = JSON.stringify(await target(root)); const result = await workflow(root, new WorkflowModel(), { writer: { write: async () => { writes += 1; throw new Error('dry-run Writer call') } } }).execute(input('dry_run')); assert.equal(result.validation?.status, 'passed'); assert.equal(result.raw.persisted, false); assert.equal(result.validation?.status, 'passed'); assert.equal(result.committedChanges.knowledgeCreated, 0); assert.equal(writes, 0); assert.equal(JSON.stringify(await target(root)), before); await assert.rejects(readFile(join(root, 'logs/ingestion/run-dry_run.yaml'), 'utf8')) } finally { await removeRuntimeKnowledgeBase(root) } })
test('section batching is deterministic, bounded, and covers every chunk exactly once', async () => { const root = await createV03Root('readonly'); try { const chunks = Array.from({ length: 5 }, (_, index) => ({ chunkId: `chunk-${String(index + 1).padStart(4, '0')}`, text: `Chunk ${index + 1}. ` + 'x'.repeat(2500), section: 'Long Section' })); const text = chunks.map((chunk) => chunk.text).join('\n'); const model = new WorkflowModel(); const original = model.invoke.bind(model); model.invoke = async (request) => { const value = await original(request); if (request.operation !== 'extractKnowledge') return value; const first = (request.input as { batch: { chunks: Array<{ chunkId: string }> } }).batch.chunks[0]!.chunkId; return { ...(value as { entities: Array<Record<string, unknown>>; relations: Array<Record<string, unknown>>; claims: Array<Record<string, unknown>> }), entities: (value as { entities: Array<Record<string, unknown>> }).entities.map((item) => ({ ...item, evidenceChunkRefs: [first] })), relations: (value as { relations: Array<Record<string, unknown>> }).relations.map((item) => ({ ...item, evidenceChunkRefs: [first] })), claims: (value as { claims: Array<Record<string, unknown>> }).claims.map((item) => ({ ...item, evidenceChunkRefs: [first] })) }; }; const result = await workflow(root, model, { inputResolver: { resolve: async () => ({ rawBytes: new TextEncoder().encode(text), originalFilename: null, mediaType: 'text/plain', normalizedText: text, chunks }) } }).execute(input('dry_run', text)); assert.equal(result.batches.chunkCount, 5); assert.equal(new Set(result.batches.chunkIds).size, result.batches.chunkIds.length); assert.equal(result.batches.batches.reduce((sum, batch) => sum + batch.chunkIds.length, 0), 5); assert.ok(result.batches.batches.every((batch) => batch.characterCount <= 6000)); assert.equal(model.requests.filter((request) => request.operation === 'extractKnowledge').length, result.batches.batchCount) } finally { await removeRuntimeKnowledgeBase(root) } })
test('ChangeSet model-call accounting uses actual model invocations, not decision count', async () => { const root = await createV03Root('readonly'); try { const chunks = [{ chunkId: 'chunk-0001', text: 'A'.repeat(4000), section: 'Section A' }, { chunkId: 'chunk-0002', text: 'B'.repeat(4000), section: 'Section B' }]; const model = new WorkflowModel(); const original = model.invoke.bind(model); model.invoke = async (request) => { const value = await original(request); if (request.operation !== 'extractKnowledge') return value; const first = (request.input as { batch: { chunks: Array<{ chunkId: string }> } }).batch.chunks[0]!.chunkId; return { ...(value as { entities: Array<Record<string, unknown>>; relations: Array<Record<string, unknown>>; claims: Array<Record<string, unknown>> }), entities: (value as { entities: Array<Record<string, unknown>> }).entities.map((item) => ({ ...item, evidenceChunkRefs: [first] })), relations: (value as { relations: Array<Record<string, unknown>> }).relations.map((item) => ({ ...item, evidenceChunkRefs: [first] })), claims: (value as { claims: Array<Record<string, unknown>> }).claims.map((item) => ({ ...item, evidenceChunkRefs: [first] })) }; }; let changeSet: Record<string, unknown> | undefined; const result = await workflow(root, model, { inputResolver: { resolve: async () => ({ rawBytes: new TextEncoder().encode('two-batch-input'), originalFilename: null, mediaType: 'text/plain', normalizedText: chunks.map((chunk) => chunk.text).join('\n'), chunks }) }, validation: { validateChangeSet: async (_handle, candidate) => { changeSet = candidate as unknown as Record<string, unknown>; return { report: { status: 'passed', errors: [], warnings: [] } as never } } } }).execute(input('dry_run')); const contextValue = changeSet?.ingestionContext as { modelCalls?: number } | undefined; assert.equal(result.modelCalls.length, 4); assert.equal(result.reconciliation.candidates, 3); assert.equal(contextValue?.modelCalls, 4); assert.notEqual(contextValue?.modelCalls, result.reconciliation.candidates) } finally { await removeRuntimeKnowledgeBase(root) } })
test('new Theme proposals remain review-only and do not auto-create a Theme', async () => { const root = await createV03Root('readonly'); try { const model = new WorkflowModel(); const original = model.invoke.bind(model); model.invoke = async (request) => { const value = await original(request); return request.operation === 'understandReport' ? { ...(value as object), themeHypotheses: [{ mention: 'Uncatalogued Theme', disposition: 'proposed_new', existingThemeRefs: [], reason: 'Not in catalog.', evidenceChunkRefs: ['chunk-0001'] }], newThemeProposal: { name: 'Uncatalogued Theme', definition: 'Review needed.', reason: 'New theme.' } } : value }; const result = await workflow(root, model).execute(input('dry_run')); assert.equal(result.status, 'completed_with_review'); assert.equal(result.themeHandling.dispositions.proposed_new, 1); assert.equal(result.plannedChanges.knowledgeCreate.some((id) => id.startsWith('entity:')), true); assert.equal(result.plannedChanges.knowledgeCreate.some((id) => id.includes('theme')), false) } finally { await removeRuntimeKnowledgeBase(root) } })
test('review isolation commits independent safe Knowledge while excluding the review closure', async () => { const root = await createV03Root(); try { const model = new WorkflowModel(); const original = model.invoke.bind(model); model.invoke = async (request) => { const value = await original(request); if (request.operation !== 'reconcileKnowledge') return value; return { decisions: (value as { decisions: Array<Record<string, unknown>> }).decisions.map((decision) => String(decision.candidateId).includes('-relation-') ? { ...decision, decision: 'user_review', classification: 'relation_conflict', requiresUserReview: true, reason: 'Relation requires review.' } : decision) }; }; const result = await workflow(root, model).execute(input('commit')); assert.equal(result.status, 'completed_with_review', JSON.stringify(result.errors)); assert.equal(result.finalRevision, 1); assert.equal(result.committedChanges.knowledgeCreated, 2); assert.equal(result.reviewItems.some((item) => item.category === 'relation_conflict'), true); assert.equal(result.source?.resolution, 'source_create') } finally { await removeRuntimeKnowledgeBase(root) } })
test('review-only semantic input persists Raw but does not force Source or revision', async () => { const root = await createV03Root(); try { const model = new WorkflowModel(); const original = model.invoke.bind(model); model.invoke = async (request) => { const value = await original(request); return request.operation === 'reconcileKnowledge' ? { decisions: (value as { decisions: Array<Record<string, unknown>> }).decisions.map((decision) => ({ ...decision, decision: 'user_review', classification: 'fact_conflict', requiresUserReview: true, reason: 'All candidates require review.' })) } : value }; const result = await workflow(root, model).execute(input('commit')); assert.equal(result.status, 'completed_with_review'); assert.equal(result.raw.persisted, true); assert.equal(result.source, null); assert.equal(result.finalRevision, 0); assert.equal(result.committedChanges.knowledgeCreated, 0); assert.equal((await target(root)).index.sources.size, 0) } finally { await removeRuntimeKnowledgeBase(root) } })
test('conditional Schema Gap analysis isolates only the signalled candidate', async () => { const root = await createV03Root(); try { const model = new WorkflowModel(); const original = model.invoke.bind(model); model.invoke = async (request) => { const value = await original(request); if (request.operation === 'extractKnowledge') { const extraction = value as { entities: Array<Record<string, unknown>>; relations: Array<Record<string, unknown>>; claims: Array<Record<string, unknown>> }; return { entities: extraction.entities.map((item) => ({ ...item, semanticFields: { schemaGap: true } })), relations: extraction.relations, claims: extraction.claims }; } if (request.operation === 'analyzeSchemaGaps') return { gaps: [{ candidateRefs: ['candidate-batch-0001-entity-0001'], gapType: 'schema', observedInformation: { description: 'Unrepresentable attribute.', examples: ['x'] }, currentLimitation: { description: 'No canonical field.' }, suggestedDirection: { description: 'Review schema.' }, affectedKnowledgeTypes: ['entity'], affectedIndustries: ['semiconductor'], generality: 'local', frequency: 'first_seen', recommendedAction: 'review' }] }; return value }; const result = await workflow(root, model).execute(input('commit')); assert.equal(result.status, 'completed_with_review'); assert.equal(result.schemaGaps.length, 1); assert.equal(result.committedChanges.knowledgeCreated, 2); assert.equal(result.reviewItems.some((item) => item.category === 'schema_gap'), true) } finally { await removeRuntimeKnowledgeBase(root) } })
test('model calls expose four v0.3 operations with retryCount zero and no legacy operation', async () => { const root = await createV03Root('readonly'); try { const model = new WorkflowModel(); const result = await workflow(root, model).execute(input('dry_run')); assert.ok(result.modelCalls.every((call) => call.retryCount === 0)); assert.ok(result.modelCalls.every((call) => ['understandReport', 'extractKnowledge', 'reconcileKnowledge', 'analyzeSchemaGaps'].includes(call.operation))); assert.equal(result.modelCalls.some((call) => call.operation === 'analyzeSchemaGaps'), false); assert.equal(model.requests.some((request) => request.operation === 'assessSource'), false) } finally { await removeRuntimeKnowledgeBase(root) } })
test('identical successful ingestion is idempotent when reprocess is false', async () => { const root = await createV03Root(); try { const first = await workflow(root).execute(input('commit')); const secondInput = { ...input('commit'), workflowRunId: 'run-second' }; const second = await workflow(root).execute(secondInput); assert.equal(first.finalRevision, 1); assert.equal(second.status, 'completed'); assert.equal(second.finalRevision, 1); assert.equal(second.committedChanges.knowledgeCreated, 0) } finally { await removeRuntimeKnowledgeBase(root) } })
test('a failed required extraction batch blocks semantic commit and preserves revision', async () => { const root = await createV03Root(); try { const model = new WorkflowModel(); model.invoke = async (request) => { if (request.operation === 'extractKnowledge') return { entities: [{ entityType: 'company', name: 'Bad', aliases: [], description: null, suggestedExistingRef: null, semanticFields: {}, evidenceChunkRefs: ['missing'], reason: 'bad' }], relations: [], claims: [] }; return request.operation === 'understandReport' ? understanding() : request.operation === 'reconcileKnowledge' ? { decisions: [] } : { gaps: [] } }; const result = await workflow(root, model).execute(input('commit')); assert.equal(result.status, 'blocked'); assert.equal(result.finalRevision, 0); assert.equal(result.errors[0]?.code, 'invalid_reference'); const state = await target(root); assert.equal(state.handle.revision, 0) } finally { await removeRuntimeKnowledgeBase(root) } })
test('Source identity is deterministic and all report provenance is bound to Source plus Raw', async () => { const root = await createV03Root(); try { const first = await workflow(root).execute(input('commit')); assert.ok(first.source?.sourceId.startsWith('source:')); const state = await target(root); const claim = [...state.index.claims.values()][0]!; assert.equal(claim.sourceRefs?.includes(first.source!.sourceId), true); assert.equal(claim.provenance?.[0]?.sourceRef, first.source!.sourceId); assert.equal(claim.provenance?.[0]?.rawRef, first.raw.rawRef); const bytes = new TextEncoder().encode(input('commit').report.inputRef.text); assert.equal(first.raw.rawRef, deriveRawIdentity(bytes).rawRef) } finally { await removeRuntimeKnowledgeBase(root) } })
test('an existing reliable Source identity is resolved and merged in the same ChangeSet', async () => { const root = await createV03Root(); try { const identity = 'https://example.test/report|2026-08-26|Workflow Report|Research House'; const sourceId = `source:doc-${createHash('sha256').update(identity).digest('hex').slice(0, 16)}`; await put(root, 'sources/existing.yaml', { id: sourceId, title: 'Workflow Report', publisher: 'Research House', publishedAt: '2026-08-26', url: 'https://example.test/report', sourceType: 'professional_media', sourceReliability: 'medium', lifecycle: { status: 'active' } }); const registry = JSON.parse(await readFile(join(root, 'registry/assets.yaml'), 'utf8')) as Record<string, unknown>; registry[sourceId] = { type: 'source', storageRef: 'sources/existing.yaml' }; await put(root, 'registry/assets.yaml', registry); const result = await workflow(root).execute(input('commit')); assert.equal(result.source?.resolution, 'source_merge'); assert.deepEqual(result.plannedChanges.sourceMerge, [sourceId]); assert.equal((await target(root)).index.getSource(sourceId).rawRefs?.length, 1) } finally { await removeRuntimeKnowledgeBase(root) } })
test('sparse reports include RawRef in Source identity and cannot collide', async () => { const root = await createV03Root('readonly'); try { const sparse = { title: null, publisher: null, institution: null, author: null, publishedAt: null, sourceUrl: null }; const first = await workflow(root, new WorkflowModel()).execute({ ...input('dry_run', 'Sparse report A', sparse), workflowRunId: 'run-sparse-a' }); const second = await workflow(root, new WorkflowModel()).execute({ ...input('dry_run', 'Sparse report B', sparse), workflowRunId: 'run-sparse-b' }); assert.equal(first.source?.resolution, 'source_create'); assert.equal(second.source?.resolution, 'source_create'); assert.notEqual(first.source?.sourceId, second.source?.sourceId); assert.notDeepEqual(first.plannedChanges.sourceCreate, second.plannedChanges.sourceCreate) } finally { await removeRuntimeKnowledgeBase(root) } })
test('workflow target stays native and never uses legacy Intelligence or retired result counters', async () => { const root = await createV03Root('readonly'); try { const result = await workflow(root).execute(input('dry_run')); const serialized = JSON.stringify(result); for (const retired of ['filtering', 'admitted', 'mapped', 'partiallyMapped', 'unmapped', 'Intelligence', 'assessSource', 'expectedOutputContract']) assert.equal(serialized.includes(retired), false); assert.equal((await target(root)).index.constructor.name, 'KnowledgeIndexV03') } finally { await removeRuntimeKnowledgeBase(root) } })
