import { createHash } from 'node:crypto'
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { tmpdir } from 'node:os'
import assert from 'node:assert/strict'
import test from 'node:test'
import { KNOWLEDGE_SCHEMA_V03 } from '../../../packages/schemas/knowledge/v03/executable-schema.ts'
import { KnowledgeBaseLoader, KnowledgeBaseRegistry, KnowledgeIndexV03, deriveRawIdentity } from '../../../packages/shared/knowledge-base/index.ts'
import { KnowledgeCurationError, KnowledgeCurationSkill, type KnowledgeCurationModel, type KnowledgeCurationModelRequest } from '../../../packages/skills/knowledge-curation/index.ts'
import { ResearchReportKnowledgeIngestionWorkflow, researchReportKnowledgeIngestionWorkflowDefinition } from '../../../packages/workflows/research-report-knowledge-ingestion/index.ts'
import { createRuntimeKnowledgeBase, removeRuntimeKnowledgeBase } from '../runtime/helpers.ts'

async function put(root: string, path: string, value: unknown): Promise<void> { const file = join(root, path); await mkdir(dirname(file), { recursive: true }); await writeFile(file, `${JSON.stringify(value)}\n`, 'utf8') }
async function createV03Root(status: 'active' | 'readonly' = 'active', includeExistingSemanticObjects = false): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), 'researchhub-ingestion-v03-'))
  await put(root, 'manifest.yaml', { knowledgeBaseId: 'kb-runtime-test', name: 'Workflow Fixture', schemaVersion: '0.3', storageFormatVersion: '1', revision: 0, status, createdAt: '2026-08-26T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' })
  await put(root, 'entities/company.yaml', { id: 'entity:existing', type: 'company', name: 'Example Company', aliases: ['Example'], lifecycle: { status: 'active' } })
  await put(root, 'entities/industry.yaml', { id: 'entity:semiconductor', type: 'industry', name: 'Semiconductor', lifecycle: { status: 'active' } })
  await put(root, 'registry/assets.yaml', { 'entity:existing': { type: 'entity', storageRef: 'entities/company.yaml' }, 'entity:semiconductor': { type: 'entity', storageRef: 'entities/industry.yaml' } })
  if (includeExistingSemanticObjects) {
    await put(root, 'relations/exposure.yaml', { id: 'relation:exposure', type: 'business_exposure', sourceRef: 'entity:existing', targetRef: 'entity:semiconductor', attributes: { exposureBasis: 'direct_operation', realizationStage: 'reported', materiality: 'material' }, contextRefs: [], sourceRefs: [], lifecycle: { status: 'active' }, asOf: null })
    await put(root, 'claims/revenue.yaml', { id: 'claim:revenue', claimType: 'fact', statement: 'Example Company revenue increased.', subjectRefs: ['entity:existing'], primarySubjectRef: 'entity:existing', sourceRefs: [], structuredValue: { metric: 'growth', value: 0.2, unit: 'ratio', comparator: 'approx' }, provenance: [], lifecycle: { status: 'active' } })
    await put(root, 'registry/assets.yaml', { 'entity:existing': { type: 'entity', storageRef: 'entities/company.yaml' }, 'entity:semiconductor': { type: 'entity', storageRef: 'entities/industry.yaml' }, 'relation:exposure': { type: 'relation', storageRef: 'relations/exposure.yaml' }, 'claim:revenue': { type: 'claim', storageRef: 'claims/revenue.yaml' } })
  }
  await put(root, 'registry/raw.yaml', {})
  return root
}
async function target(root: string) { const loader = new KnowledgeBaseLoader({ registry: new KnowledgeBaseRegistry() }); const handle = await loader.mount(root); const state = await loader.loadRuntimeState(handle); assert.ok(state.index instanceof KnowledgeIndexV03); return { handle, index: state.index } }
function input(mode: 'commit' | 'dry_run', text = 'Example Company operates in semiconductors and revenue increased.', metadata: Partial<{ title: string | null; publisher: string | null; institution: string | null; author: string | null; publishedAt: string | null; sourceUrl: string | null }> = {}): { workflowRunId: string; knowledgeBaseId: string; report: { inputRef: { type: 'text'; text: string }; suppliedMetadata: { title: string | null; publisher: string | null; institution: string | null; author: string | null; publishedAt: string | null; sourceUrl: string | null } }; options: { mode: 'commit' | 'dry_run'; reprocess: boolean } } { return { workflowRunId: `run-${mode}`, knowledgeBaseId: 'kb-runtime-test', report: { inputRef: { type: 'text', text }, suppliedMetadata: { title: 'Workflow Report', publisher: 'Research House', institution: null, author: 'Analyst', publishedAt: '2026-08-26', sourceUrl: 'https://example.test/report', ...metadata } }, options: { mode, reprocess: false } } }
function understanding() { return { sourceAssessment: { sourceType: 'professional_media', publisher: 'Research House', institution: null, author: 'Analyst', publishedAt: '2026-08-26', primaryOrSecondary: 'secondary', sourceReliability: 'medium', sourceIdentityConfidence: 0.9, reasoning: ['Metadata is consistent.'] }, researchScope: ['semiconductor'], majorTopics: ['revenue'], majorEntityMentions: [{ mention: 'Example Company', entityType: 'company', suggestedExistingRef: 'entity:existing', evidenceChunkRefs: ['chunk-0001'], reason: 'Named in report.' }], themeHypotheses: [], uncertainty: [] } }
function extraction() { return { entities: [{ entityType: 'company', name: 'New Company', aliases: [], description: null, suggestedExistingRef: null, semanticFields: {}, evidenceChunkRefs: ['chunk-0001'], reason: 'Named as a company.' }], relations: [{ relationType: 'business_exposure', sourceMention: { text: 'Example Company', entityType: 'company', existingRef: 'entity:existing' }, targetMention: { text: 'Semiconductor', entityType: 'industry', existingRef: 'entity:semiconductor' }, attributes: { exposureBasis: 'direct_operation', realizationStage: 'reported', materiality: 'material' }, contextMentions: [], evidenceChunkRefs: ['chunk-0001'], reason: 'Describes business exposure.' }], claims: [{ claimType: 'fact', statement: 'Example Company revenue increased.', subjectMentions: [{ text: 'Example Company', entityType: 'company', existingRef: 'entity:existing' }], temporal: null, structuredValue: { metric: 'growth', value: 0.2, unit: 'ratio', comparator: 'approx' }, semanticConfidence: 0.85, evidenceChunkRefs: ['chunk-0001'], reason: 'Direct report statement.' }] } }
class WorkflowModel implements KnowledgeCurationModel {
  readonly requests: KnowledgeCurationModelRequest[] = []
  async invoke(request: KnowledgeCurationModelRequest): Promise<unknown> { this.requests.push(request); if (request.operation === 'understandReport') return understanding(); if (request.operation === 'extractKnowledge') return extraction(); if (request.operation === 'reconcileKnowledge') { const groups = (request.input as { groups: Array<{ candidates: Array<{ candidateId: string; existingRefs: string[] }> }> }).groups; return { decisions: groups.flatMap((group) => group.candidates.map((candidate) => ({ candidateId: candidate.candidateId, decision: candidate.existingRefs.length ? 'duplicate' : 'create', classification: candidate.existingRefs.length ? 'duplicate' : 'complementary', existingRefs: candidate.existingRefs, reason: 'No duplicate beyond precise context.', requiresUserReview: false }))) } } return { gaps: [] } }
}
function extractionForBatch(request: KnowledgeCurationModelRequest): Record<string, unknown> {
  const value = extraction() as { entities: Array<Record<string, unknown>>; relations: Array<Record<string, unknown>>; claims: Array<Record<string, unknown>> }
  const batch = request.input as { batch?: { chunks?: Array<{ chunkId: string }> } }
  const chunkId = batch.batch?.chunks?.[0]?.chunkId ?? 'chunk-0001'
  return { entities: value.entities.map((item) => ({ ...item, evidenceChunkRefs: [chunkId] })), relations: value.relations.map((item) => ({ ...item, evidenceChunkRefs: [chunkId] })), claims: value.claims.map((item) => ({ ...item, evidenceChunkRefs: [chunkId] })) }
}
function extractionForChunk(chunkId: string): Record<string, unknown> { const value = extraction() as { entities: Array<Record<string, unknown>>; relations: Array<Record<string, unknown>>; claims: Array<Record<string, unknown>> }; return { entities: value.entities.map((item) => ({ ...item, evidenceChunkRefs: [chunkId] })), relations: value.relations.map((item) => ({ ...item, evidenceChunkRefs: [chunkId] })), claims: value.claims.map((item) => ({ ...item, evidenceChunkRefs: [chunkId] })) } }
class RetryWorkflowModel extends WorkflowModel {
  private readonly extractionQueues = new Map<string, unknown[]>()
  queue(batchId: string, outputs: unknown[]): this { this.extractionQueues.set(batchId, [...outputs]); return this }
  override async invoke(request: KnowledgeCurationModelRequest): Promise<unknown> {
    if (request.operation !== 'extractKnowledge') return super.invoke(request)
    this.requests.push(request)
    const batchId = (request.input as { batch: { batchId: string } }).batch.batchId
    const queue = this.extractionQueues.get(batchId)
    if (!queue || queue.length === 0) return extractionForBatch(request)
    return structuredClone(queue.length === 1 ? queue[0] : queue.shift())
  }
}
class ReconciliationRetryWorkflowModel extends WorkflowModel {
  constructor(readonly persistent = false) { super() }
  private reconcileAttempts = 0
  override async invoke(request: KnowledgeCurationModelRequest): Promise<unknown> {
    if (request.operation !== 'reconcileKnowledge') return super.invoke(request)
    this.requests.push(request)
    this.reconcileAttempts += 1
    const groups = (request.input as { groups: Array<{ candidates: Array<{ candidateId: string }> }> }).groups
    const decisions = groups.flatMap((group) => group.candidates.map((candidate, index) => ({ candidateId: candidate.candidateId, decision: 'merge_source', classification: 'duplicate', existingRefs: (this.reconcileAttempts === 1 || this.persistent) && index === 0 ? ['entity:outside'] : [], reason: 'Fixture reconciliation decision.', requiresUserReview: false })))
    if (this.reconcileAttempts === 1 || this.persistent) return { decisions }
    return { decisions: groups.flatMap((group) => group.candidates.map((candidate) => ({ candidateId: candidate.candidateId, decision: 'duplicate', classification: 'duplicate', existingRefs: candidate.existingRefs, reason: 'Corrected fixture decision.', requiresUserReview: false }))) }
  }
}
class ReconciliationModelError extends WorkflowModel {
  override async invoke(request: KnowledgeCurationModelRequest): Promise<unknown> { if (request.operation === 'reconcileKnowledge') { this.requests.push(request); throw new KnowledgeCurationError('model_error', 'reconciliation transport failure') } return super.invoke(request) }
}
function invalidExtraction(overrides: Record<string, unknown> = {}): Record<string, unknown> { const value = extraction() as Record<string, any>; return { ...value, ...overrides, entities: [{ ...(value.entities as Array<Record<string, unknown>>)[0], evidenceChunkRefs: ['chunk-unknown'] }], relations: [{ ...(value.relations as Array<Record<string, unknown>>)[0], targetMention: { text: 'Company', entityType: 'company', existingRef: null } }], claims: [{ ...(value.claims as Array<Record<string, unknown>>)[0], semanticConfidence: 2 }] } }
function candidateIdExtraction(): Record<string, unknown> { const value = extraction(); (value.entities[0] as Record<string, unknown>).candidateId = 'attacker-candidate-id'; return value }
class ExtractionModelError extends WorkflowModel {
  override async invoke(request: KnowledgeCurationModelRequest): Promise<unknown> { if (request.operation === 'extractKnowledge') { this.requests.push(request); throw new KnowledgeCurationError('model_error', 'transport failure') } return super.invoke(request) }
}
function modelSkill(model = new WorkflowModel()) { return { model, skill: new KnowledgeCurationSkill({ model }) } }
function workflow(root: string, model = new WorkflowModel(), extra: Record<string, unknown> = {}) { return new ResearchReportKnowledgeIngestionWorkflow({ targetResolver: { resolve: async () => target(root) }, curation: new KnowledgeCurationSkill({ model }), ...extra }) }

test('workflow definition is the frozen eighteen-stage v0.3 sequence', () => { assert.equal(researchReportKnowledgeIngestionWorkflowDefinition.version, '0.3'); assert.equal(researchReportKnowledgeIngestionWorkflowDefinition.steps.length, 18); assert.equal(researchReportKnowledgeIngestionWorkflowDefinition.steps[0]?.id, 'intake-execution-identity'); assert.equal(researchReportKnowledgeIngestionWorkflowDefinition.steps[17]?.id, 'final-result-log-refresh'); assert.equal(researchReportKnowledgeIngestionWorkflowDefinition.steps[6]?.skill, 'knowledge-access'); assert.equal(researchReportKnowledgeIngestionWorkflowDefinition.steps[11]?.skill, 'knowledge-access') })

test('accepts only native Schema 0.3 / Storage 1 and rejects a Schema 0.2 commit', async () => { const root = await createRuntimeKnowledgeBase(); try { const legacyLoader = new KnowledgeBaseLoader({ registry: new KnowledgeBaseRegistry() }); const result = await new ResearchReportKnowledgeIngestionWorkflow({ targetResolver: { resolve: async () => ({ handle: await legacyLoader.mount(root), index: {} as KnowledgeIndexV03 }) }, curation: new KnowledgeCurationSkill({ model: new WorkflowModel() }) }).execute(input('commit')); assert.equal(result.status, 'blocked'); assert.equal(result.errors[0]?.code, 'unsupported_schema'); assert.match(result.errors[0]?.message ?? '', /0\.3/) } finally { await removeRuntimeKnowledgeBase(root) } })
test('requires an active writable target for commit but permits readable readonly dry-run', async () => { const root = await createV03Root('readonly'); try { const commit = await workflow(root).execute(input('commit')); assert.equal(commit.status, 'blocked'); assert.equal(commit.errors[0]?.code, 'target_not_writable'); const dry = await workflow(root).execute(input('dry_run')); assert.notEqual(dry.status, 'blocked'); assert.equal(dry.raw.persisted, false); assert.equal(dry.validation?.status, 'passed'); assert.equal(dry.finalRevision, 0) } finally { await removeRuntimeKnowledgeBase(root) } })
test('commit archives Raw first, creates deterministic new objects without reconciliation, and reloads native v0.3 state', async () => { const root = await createV03Root(); try { const model = new WorkflowModel(); const result = await workflow(root, model).execute(input('commit')); assert.equal(result.status, 'completed', JSON.stringify(result.errors)); assert.equal(result.raw.persisted, true); assert.equal(result.raw.created, true); assert.equal(result.source?.resolution, 'source_create'); assert.equal(result.plannedChanges.knowledgeCreate.length, 3); assert.equal(result.committedChanges.knowledgeCreated, 3); assert.equal(result.finalRevision, 1); assert.equal(result.reconciliation.candidates, 0); assert.equal(model.requests.filter((request) => request.operation === 'understandReport').length, 1); assert.equal(model.requests.filter((request) => request.operation === 'extractKnowledge').length, result.batches.batchCount); assert.equal(model.requests.filter((request) => request.operation === 'reconcileKnowledge').length, 0); const reloaded = await target(root); assert.equal(reloaded.index.entities.size, 3); assert.equal(reloaded.index.relations.size, 1); assert.equal(reloaded.index.claims.size, 1); assert.equal((await new (await import('../../../packages/skills/knowledge-validation/index.ts')).KnowledgeValidationSkill({ loader: new KnowledgeBaseLoader() }).validateKnowledgeBase(reloaded.handle)).status, 'passed'); const log = await readFile(join(root, 'logs/ingestion/run-commit.yaml'), 'utf8'); assert.match(log, /completed/) } finally { await removeRuntimeKnowledgeBase(root) } })

test('existing endpoints do not make a new relation or claim eligible for reconciliation', async () => { const root = await createV03Root('readonly'); try { const model = new WorkflowModel(); const result = await workflow(root, model).execute(input('dry_run')); assert.equal(result.status, 'completed'); assert.equal(result.reconciliation.candidates, 0); assert.equal(model.requests.filter((request) => request.operation === 'reconcileKnowledge').length, 0); assert.equal(result.plannedChanges.knowledgeCreate.length, 3) } finally { await removeRuntimeKnowledgeBase(root) } })

test('only true existing Entity, Relation, and Claim matches enter reconciliation with target refs isolated', async () => { const root = await createV03Root('readonly', true); try { const model = new WorkflowModel(); const original = model.invoke.bind(model); model.invoke = async (request) => { const value = await original(request); if (request.operation !== 'extractKnowledge') return value; const extractionValue = value as { entities: Array<Record<string, unknown>>; relations: Array<Record<string, unknown>>; claims: Array<Record<string, unknown>> }; return { ...extractionValue, entities: extractionValue.entities.map((entity) => ({ ...entity, name: 'Example Company', suggestedExistingRef: 'entity:existing' })) } }; const result = await workflow(root, model).execute(input('dry_run')); assert.equal(result.status, 'completed', JSON.stringify(result.errors)); const reconcileRequest = model.requests.find((request) => request.operation === 'reconcileKnowledge')!; const groups = (reconcileRequest.input as any).groups as Array<{ candidates: Array<{ kind: string; existingRefs: string[] }>; existingKnowledge: Array<{ id: string }> }>; assert.equal(groups.length, 1); assert.deepEqual(groups[0]!.candidates.map((candidate) => [candidate.kind, candidate.existingRefs]), [['entity', ['entity:existing']], ['relation', ['relation:exposure']], ['claim', ['claim:revenue']]]); assert.deepEqual(groups[0]!.existingKnowledge.map((item) => item.id).sort(), ['claim:revenue', 'entity:existing', 'entity:semiconductor', 'relation:exposure']); assert.equal(result.reconciliation.candidates, 3) } finally { await removeRuntimeKnowledgeBase(root) } })

test('reconciliation invalid_reference retries once with group observability and no prior output', async () => { const root = await createV03Root('readonly', true); try { const model = new ReconciliationRetryWorkflowModel(); const result = await workflow(root, model).execute(input('dry_run')); const requests = model.requests.filter((request) => request.operation === 'reconcileKnowledge'); const call = result.modelCalls.find((item) => item.operation === 'reconcileKnowledge')!; assert.equal(result.status, 'completed', JSON.stringify(result.errors)); assert.equal(requests.length, 2); assert.equal(call.retryCount, 1); assert.equal(call.groupId, 'reconciliation-0001'); assert.equal(call.validationFailures?.[0]?.code, 'invalid_reference'); assert.deepEqual(requests[0]?.input, requests[1]?.input); assert.doesNotMatch(requests[1]?.instruction ?? '', /entity:outside/); } finally { await removeRuntimeKnowledgeBase(root) } })

test('persistent reconciliation validation failure stops after exactly two physical calls', async () => { const root = await createV03Root('readonly', true); try { const model = new ReconciliationRetryWorkflowModel(true); const result = await workflow(root, model).execute(input('dry_run')); const call = result.modelCalls.find((item) => item.operation === 'reconcileKnowledge')!; assert.equal(result.status, 'blocked'); assert.equal(result.errors[0]?.code, 'invalid_reference'); assert.equal(model.requests.filter((request) => request.operation === 'reconcileKnowledge').length, 2); assert.equal(call.retryCount, 1); assert.equal(call.validationFailures?.length, 2) } finally { await removeRuntimeKnowledgeBase(root) } })

test('reconciliation model and transport failures do not retry', async () => { const root = await createV03Root('readonly', true); try { const model = new ReconciliationModelError(); const result = await workflow(root, model).execute(input('dry_run')); const call = result.modelCalls.find((item) => item.operation === 'reconcileKnowledge')!; assert.equal(result.status, 'blocked'); assert.equal(result.errors[0]?.code, 'model_error'); assert.equal(model.requests.filter((request) => request.operation === 'reconcileKnowledge').length, 1); assert.equal(call.retryCount, 0); assert.equal(call.validationFailures, undefined) } finally { await removeRuntimeKnowledgeBase(root) } })
test('dry-run reaches final validation without Raw, Source, receipt, Writer, or mutation', async () => { const root = await createV03Root('readonly'); try { let writes = 0; const before = JSON.stringify(await target(root)); const result = await workflow(root, new WorkflowModel(), { writer: { write: async () => { writes += 1; throw new Error('dry-run Writer call') } } }).execute(input('dry_run')); assert.equal(result.validation?.status, 'passed'); assert.equal(result.raw.persisted, false); assert.equal(result.validation?.status, 'passed'); assert.equal(result.committedChanges.knowledgeCreated, 0); assert.equal(writes, 0); assert.equal(JSON.stringify(await target(root)), before); await assert.rejects(readFile(join(root, 'logs/ingestion/run-dry_run.yaml'), 'utf8')) } finally { await removeRuntimeKnowledgeBase(root) } })
test('section batching is deterministic, bounded, and covers every chunk exactly once', async () => { const root = await createV03Root('readonly'); try { const chunks = Array.from({ length: 5 }, (_, index) => ({ chunkId: `chunk-${String(index + 1).padStart(4, '0')}`, text: `Chunk ${index + 1}. ` + 'x'.repeat(2500), section: 'Long Section' })); const text = chunks.map((chunk) => chunk.text).join('\n'); const model = new WorkflowModel(); const original = model.invoke.bind(model); model.invoke = async (request) => { const value = await original(request); if (request.operation !== 'extractKnowledge') return value; const first = (request.input as { batch: { chunks: Array<{ chunkId: string }> } }).batch.chunks[0]!.chunkId; return { ...(value as { entities: Array<Record<string, unknown>>; relations: Array<Record<string, unknown>>; claims: Array<Record<string, unknown>> }), entities: (value as { entities: Array<Record<string, unknown>> }).entities.map((item) => ({ ...item, evidenceChunkRefs: [first] })), relations: (value as { relations: Array<Record<string, unknown>> }).relations.map((item) => ({ ...item, evidenceChunkRefs: [first] })), claims: (value as { claims: Array<Record<string, unknown>> }).claims.map((item) => ({ ...item, evidenceChunkRefs: [first] })) }; }; const result = await workflow(root, model, { inputResolver: { resolve: async () => ({ rawBytes: new TextEncoder().encode(text), originalFilename: null, mediaType: 'text/plain', normalizedText: text, chunks }) } }).execute(input('dry_run', text)); assert.equal(result.batches.chunkCount, 5); assert.equal(new Set(result.batches.chunkIds).size, result.batches.chunkIds.length); assert.equal(result.batches.batches.reduce((sum, batch) => sum + batch.chunkIds.length, 0), 5); assert.ok(result.batches.batches.every((batch) => batch.characterCount <= 6000)); assert.equal(model.requests.filter((request) => request.operation === 'extractKnowledge').length, result.batches.batchCount) } finally { await removeRuntimeKnowledgeBase(root) } })
test('ChangeSet model-call accounting uses actual model invocations, not decision count', async () => { const root = await createV03Root('readonly'); try { const chunks = [{ chunkId: 'chunk-0001', text: 'A'.repeat(4000), section: 'Section A' }, { chunkId: 'chunk-0002', text: 'B'.repeat(4000), section: 'Section B' }]; const model = new WorkflowModel(); const original = model.invoke.bind(model); model.invoke = async (request) => { const value = await original(request); if (request.operation !== 'extractKnowledge') return value; const first = (request.input as { batch: { chunks: Array<{ chunkId: string }> } }).batch.chunks[0]!.chunkId; return { ...(value as { entities: Array<Record<string, unknown>>; relations: Array<Record<string, unknown>>; claims: Array<Record<string, unknown>> }), entities: (value as { entities: Array<Record<string, unknown>> }).entities.map((item) => ({ ...item, evidenceChunkRefs: [first] })), relations: (value as { relations: Array<Record<string, unknown>> }).relations.map((item) => ({ ...item, evidenceChunkRefs: [first] })), claims: (value as { claims: Array<Record<string, unknown>> }).claims.map((item) => ({ ...item, evidenceChunkRefs: [first] })) }; }; let changeSet: Record<string, unknown> | undefined; const result = await workflow(root, model, { inputResolver: { resolve: async () => ({ rawBytes: new TextEncoder().encode('two-batch-input'), originalFilename: null, mediaType: 'text/plain', normalizedText: chunks.map((chunk) => chunk.text).join('\n'), chunks }) }, validation: { validateChangeSet: async (_handle, candidate) => { changeSet = candidate as unknown as Record<string, unknown>; return { report: { status: 'passed', errors: [], warnings: [] } as never } } } }).execute(input('dry_run')); const contextValue = changeSet?.ingestionContext as { modelCalls?: number } | undefined; assert.equal(result.modelCalls.length, 3); assert.equal(result.reconciliation.candidates, 0); assert.equal(contextValue?.modelCalls, 3); assert.notEqual(contextValue?.modelCalls, result.reconciliation.candidates) } finally { await removeRuntimeKnowledgeBase(root) } })
test('new Theme proposals remain review-only and do not auto-create a Theme', async () => { const root = await createV03Root('readonly'); try { const model = new WorkflowModel(); const original = model.invoke.bind(model); model.invoke = async (request) => { const value = await original(request); return request.operation === 'understandReport' ? { ...(value as object), themeHypotheses: [{ mention: 'Uncatalogued Theme', disposition: 'proposed_new', existingThemeRefs: [], reason: 'Not in catalog.', evidenceChunkRefs: ['chunk-0001'] }], newThemeProposal: { name: 'Uncatalogued Theme', definition: 'Review needed.', reason: 'New theme.' } } : value }; const result = await workflow(root, model).execute(input('dry_run')); assert.equal(result.status, 'completed_with_review'); assert.equal(result.themeHandling.dispositions.proposed_new, 1); assert.equal(result.plannedChanges.knowledgeCreate.some((id) => id.startsWith('entity:')), true); assert.equal(result.plannedChanges.knowledgeCreate.some((id) => id.includes('theme')), false) } finally { await removeRuntimeKnowledgeBase(root) } })
test('review isolation commits independent safe Knowledge while excluding the review closure', async () => { const root = await createV03Root('active', true); try { const model = new WorkflowModel(); const original = model.invoke.bind(model); model.invoke = async (request) => { const value = await original(request); if (request.operation !== 'reconcileKnowledge') return value; return { decisions: (value as { decisions: Array<Record<string, unknown>> }).decisions.map((decision) => String(decision.candidateId).includes('-relation-') ? { ...decision, decision: 'user_review', classification: 'relation_conflict', requiresUserReview: true, reason: 'Relation requires review.' } : decision) }; }; const result = await workflow(root, model).execute(input('commit')); assert.equal(result.status, 'completed_with_review', JSON.stringify(result.errors)); assert.equal(result.finalRevision, 1); assert.equal(result.committedChanges.knowledgeCreated, 1); assert.equal(result.reviewItems.some((item) => item.category === 'relation_conflict'), true); assert.equal(result.source?.resolution, 'source_create') } finally { await removeRuntimeKnowledgeBase(root) } })
test('review-only semantic input persists Raw but does not force Source or revision', async () => { const root = await createV03Root('active', true); try { const model = new WorkflowModel(); const original = model.invoke.bind(model); model.invoke = async (request) => { const value = await original(request); if (request.operation === 'extractKnowledge') { const extractionValue = value as { entities: Array<Record<string, unknown>>; relations: Array<Record<string, unknown>>; claims: Array<Record<string, unknown>> }; return { ...extractionValue, entities: extractionValue.entities.map((entity) => ({ ...entity, name: 'Example Company', suggestedExistingRef: 'entity:existing' })) }; } return request.operation === 'reconcileKnowledge' ? { decisions: (value as { decisions: Array<Record<string, unknown>> }).decisions.map((decision) => ({ ...decision, decision: 'user_review', classification: 'fact_conflict', requiresUserReview: true, reason: 'All candidates require review.' })) } : value }; const result = await workflow(root, model).execute(input('commit')); assert.equal(result.status, 'completed_with_review'); assert.equal(result.raw.persisted, true); assert.equal(result.source, null); assert.equal(result.finalRevision, 0); assert.equal(result.committedChanges.knowledgeCreated, 0); assert.equal((await target(root)).index.sources.size, 0) } finally { await removeRuntimeKnowledgeBase(root) } })
test('conditional Schema Gap analysis isolates only the signalled candidate', async () => { const root = await createV03Root(); try { const model = new WorkflowModel(); const original = model.invoke.bind(model); model.invoke = async (request) => { const value = await original(request); if (request.operation === 'extractKnowledge') { const extraction = value as { entities: Array<Record<string, unknown>>; relations: Array<Record<string, unknown>>; claims: Array<Record<string, unknown>> }; return { entities: extraction.entities.map((item) => ({ ...item, semanticFields: { schemaGap: true } })), relations: extraction.relations, claims: extraction.claims }; } if (request.operation === 'analyzeSchemaGaps') return { gaps: [{ candidateRefs: ['candidate-batch-0001-entity-0001'], gapType: 'schema', observedInformation: { description: 'Unrepresentable attribute.', examples: ['x'] }, currentLimitation: { description: 'No canonical field.' }, suggestedDirection: { description: 'Review schema.' }, affectedKnowledgeTypes: ['entity'], affectedIndustries: ['semiconductor'], generality: 'local', frequency: 'first_seen', recommendedAction: 'review' }] }; return value }; const result = await workflow(root, model).execute(input('commit')); assert.equal(result.status, 'completed_with_review'); assert.equal(result.schemaGaps.length, 1); assert.equal(result.committedChanges.knowledgeCreated, 2); assert.equal(result.reviewItems.some((item) => item.category === 'schema_gap'), true) } finally { await removeRuntimeKnowledgeBase(root) } })
test('model calls expose four v0.3 operations with retryCount zero and no legacy operation', async () => { const root = await createV03Root('readonly'); try { const model = new WorkflowModel(); const result = await workflow(root, model).execute(input('dry_run')); assert.ok(result.modelCalls.every((call) => call.retryCount === 0)); assert.ok(result.modelCalls.every((call) => ['understandReport', 'extractKnowledge', 'reconcileKnowledge', 'analyzeSchemaGaps'].includes(call.operation))); assert.equal(result.modelCalls.some((call) => call.operation === 'analyzeSchemaGaps'), false) } finally { await removeRuntimeKnowledgeBase(root) } })
test('identical successful ingestion is idempotent when reprocess is false', async () => { const root = await createV03Root(); try { const first = await workflow(root).execute(input('commit')); const secondInput = { ...input('commit'), workflowRunId: 'run-second' }; const second = await workflow(root).execute(secondInput); assert.equal(first.finalRevision, 1); assert.equal(second.status, 'completed'); assert.equal(second.finalRevision, 1); assert.equal(second.committedChanges.knowledgeCreated, 0) } finally { await removeRuntimeKnowledgeBase(root) } })
test('a failed required extraction batch blocks semantic commit and preserves revision', async () => { const root = await createV03Root(); try { const model = new WorkflowModel(); model.invoke = async (request) => { if (request.operation === 'extractKnowledge') return { entities: [{ entityType: 'company', name: 'Bad', aliases: [], description: null, suggestedExistingRef: null, semanticFields: {}, evidenceChunkRefs: ['missing'], reason: 'bad' }], relations: [], claims: [] }; return request.operation === 'understandReport' ? understanding() : request.operation === 'reconcileKnowledge' ? { decisions: [] } : { gaps: [] } }; const result = await workflow(root, model).execute(input('commit')); assert.equal(result.status, 'blocked'); assert.equal(result.finalRevision, 0); assert.equal(result.errors[0]?.code, 'candidate_set_exhausted'); const state = await target(root); assert.equal(state.handle.revision, 0) } finally { await removeRuntimeKnowledgeBase(root) } })
test('Source identity is deterministic and all report provenance is bound to Source plus Raw', async () => { const root = await createV03Root(); try { const first = await workflow(root).execute(input('commit')); assert.ok(first.source?.sourceId.startsWith('source:')); const state = await target(root); const claim = [...state.index.claims.values()][0]!; assert.equal(claim.sourceRefs?.includes(first.source!.sourceId), true); assert.equal(claim.provenance?.[0]?.sourceRef, first.source!.sourceId); assert.equal(claim.provenance?.[0]?.rawRef, first.raw.rawRef); const bytes = new TextEncoder().encode(input('commit').report.inputRef.text); assert.equal(first.raw.rawRef, deriveRawIdentity(bytes).rawRef) } finally { await removeRuntimeKnowledgeBase(root) } })
test('an existing reliable Source identity is resolved and merged in the same ChangeSet', async () => { const root = await createV03Root(); try { const identity = 'https://example.test/report|2026-08-26|Workflow Report|Research House'; const sourceId = `source:doc-${createHash('sha256').update(identity).digest('hex').slice(0, 16)}`; await put(root, 'sources/existing.yaml', { id: sourceId, title: 'Workflow Report', publisher: 'Research House', publishedAt: '2026-08-26', url: 'https://example.test/report', sourceType: 'professional_media', sourceReliability: 'medium', lifecycle: { status: 'active' } }); const registry = JSON.parse(await readFile(join(root, 'registry/assets.yaml'), 'utf8')) as Record<string, unknown>; registry[sourceId] = { type: 'source', storageRef: 'sources/existing.yaml' }; await put(root, 'registry/assets.yaml', registry); const result = await workflow(root).execute(input('commit')); assert.equal(result.source?.resolution, 'source_merge'); assert.deepEqual(result.plannedChanges.sourceMerge, [sourceId]); assert.equal((await target(root)).index.getSource(sourceId).rawRefs?.length, 1) } finally { await removeRuntimeKnowledgeBase(root) } })
test('sparse reports include RawRef in Source identity and cannot collide', async () => { const root = await createV03Root('readonly'); try { const sparse = { title: null, publisher: null, institution: null, author: null, publishedAt: null, sourceUrl: null }; const first = await workflow(root, new WorkflowModel()).execute({ ...input('dry_run', 'Sparse report A', sparse), workflowRunId: 'run-sparse-a' }); const second = await workflow(root, new WorkflowModel()).execute({ ...input('dry_run', 'Sparse report B', sparse), workflowRunId: 'run-sparse-b' }); assert.equal(first.source?.resolution, 'source_create'); assert.equal(second.source?.resolution, 'source_create'); assert.notEqual(first.source?.sourceId, second.source?.sourceId); assert.notDeepEqual(first.plannedChanges.sourceCreate, second.plannedChanges.sourceCreate) } finally { await removeRuntimeKnowledgeBase(root) } })
test('workflow target stays native and never uses legacy Intelligence or retired result counters', async () => { const root = await createV03Root('readonly'); try { const result = await workflow(root).execute(input('dry_run')); const serialized = JSON.stringify(result); for (const retired of ['filtering', 'admitted', 'mapped', 'partiallyMapped', 'unmapped', 'Intelligence']) assert.equal(serialized.includes(retired), false); assert.equal((await target(root)).index.constructor.name, 'KnowledgeIndexV03') } finally { await removeRuntimeKnowledgeBase(root) } })

test('recoverable extraction validation failure retries exactly once and accounts for the physical call', async () => { const root = await createV03Root('readonly'); try { const model = new RetryWorkflowModel().queue('batch-0001', [invalidExtraction(), extraction()]); let changeSet: Record<string, unknown> | undefined; const result = await workflow(root, model, { validation: { validateChangeSet: async (_handle, candidate) => { changeSet = candidate as unknown as Record<string, unknown>; return { report: { status: 'passed', errors: [], warnings: [] } as never } } } }).execute(input('dry_run')); const extractionCall = result.modelCalls.find((call) => call.operation === 'extractKnowledge')!; const extractionRequests = model.requests.filter((request) => request.operation === 'extractKnowledge'); assert.equal(result.status, 'completed', JSON.stringify(result.errors)); assert.equal(extractionRequests.length, 2); assert.equal(extractionCall.retryCount, 1); assert.equal(extractionCall.validationFailures?.[0]?.code, 'candidate_set_exhausted'); assert.equal(extractionCall.candidateValidation?.attempts.length, 2); assert.deepEqual(extractionCall.candidateValidation?.attempts[0]?.rejected, { entity: 1, relation: 1, claim: 1 }); assert.deepEqual(extractionCall.candidateValidation?.attempts[1]?.accepted, { entity: 1, relation: 1, claim: 1 }); assert.match(extractionRequests[1]?.instruction ?? '', /Validation code: candidate_set_exhausted/); assert.doesNotMatch(extractionRequests[1]?.instruction ?? '', /Example Company|Describes business exposure/); assert.deepEqual(extractionRequests[0]?.input, extractionRequests[1]?.input); assert.equal(JSON.stringify(extractionRequests[1]?.input).includes('document'), false); assert.equal(changeSet?.ingestionContext && (changeSet.ingestionContext as { modelCalls: number }).modelCalls, 3); assert.equal(result.modelCalls.reduce((sum, call) => sum + 1 + call.retryCount, 0), 3) } finally { await removeRuntimeKnowledgeBase(root) } })

test('invalid_reference extraction failure retries and preserves the C8 model projection', async () => { const root = await createV03Root('readonly'); try { const bad = extraction(); (bad.entities[0] as Record<string, unknown>).evidenceChunkRefs = ['chunk-unknown']; (bad.entities[0] as Record<string, unknown>).id = 'entity:attacker'; const model = new RetryWorkflowModel().queue('batch-0001', [bad, extraction()]); const result = await workflow(root, model).execute(input('dry_run')); const extractionCall = result.modelCalls.find((call) => call.operation === 'extractKnowledge')!; const extractionRequests = model.requests.filter((request) => request.operation === 'extractKnowledge'); assert.equal(result.status, 'completed'); assert.equal(extractionCall.retryCount, 1); assert.equal(extractionCall.validationFailures?.[0]?.code, 'invalid_reference'); assert.equal(extractionRequests.length, 2); assert.deepEqual(extractionRequests[0]?.input, extractionRequests[1]?.input); const serialized = JSON.stringify(extractionRequests[1]?.input); assert.equal(serialized.includes('chunk-unknown'), false); assert.equal(serialized.includes('normalizedText'), false); assert.equal(serialized.includes('claims'), false); assert.equal(serialized.includes('sources'), false) } finally { await removeRuntimeKnowledgeBase(root) } })

test('persistent extraction validation failure has no third attempt and retains both validation failures', async () => { const root = await createV03Root('readonly'); try { const model = new RetryWorkflowModel().queue('batch-0001', [invalidExtraction(), invalidExtraction()]); const result = await workflow(root, model).execute(input('dry_run')); const extractionCall = result.modelCalls.find((call) => call.operation === 'extractKnowledge')!; assert.equal(result.status, 'blocked'); assert.equal(result.failureStage, 'extraction'); assert.equal(result.errors[0]?.code, 'candidate_set_exhausted'); assert.equal(model.requests.filter((request) => request.operation === 'extractKnowledge').length, 2); assert.equal(extractionCall.retryCount, 1); assert.equal(extractionCall.validationFailures?.length, 2); assert.deepEqual(extractionCall.candidateValidation?.attempts.map((attempt) => attempt.rejected), [{ entity: 1, relation: 1, claim: 1 }, { entity: 1, relation: 1, claim: 1 }]) } finally { await removeRuntimeKnowledgeBase(root) } })

test('model_error extraction failure does not retry', async () => { const root = await createV03Root('readonly'); try { const model = new ExtractionModelError(); const result = await workflow(root, model).execute(input('dry_run')); const extractionCall = result.modelCalls.find((call) => call.operation === 'extractKnowledge')!; assert.equal(result.status, 'blocked'); assert.equal(result.errors[0]?.code, 'model_error'); assert.equal(model.requests.filter((request) => request.operation === 'extractKnowledge').length, 1); assert.equal(extractionCall.retryCount, 0); assert.equal(extractionCall.validationFailures, undefined) } finally { await removeRuntimeKnowledgeBase(root) } })

test('actual call accounting counts one retry across two logical extraction batches', async () => { const root = await createV03Root('readonly'); try { const chunks = [{ chunkId: 'chunk-0001', text: 'A'.repeat(4000), section: 'Section A' }, { chunkId: 'chunk-0002', text: 'B'.repeat(4000), section: 'Section B' }]; const model = new RetryWorkflowModel().queue('batch-0001', [{ entities: [], relations: [], claims: [] }]).queue('batch-0003', [invalidExtraction(), { entities: [], relations: [], claims: [] }]); let changeSet: Record<string, unknown> | undefined; const result = await workflow(root, model, { inputResolver: { resolve: async () => ({ rawBytes: new TextEncoder().encode('two-batch-input'), originalFilename: null, mediaType: 'text/plain', normalizedText: chunks.map((chunk) => chunk.text).join('\n'), chunks }) }, validation: { validateChangeSet: async (_handle, candidate) => { changeSet = candidate as unknown as Record<string, unknown>; return { report: { status: 'passed', errors: [], warnings: [] } as never } } } }).execute(input('dry_run')); assert.equal(result.status, 'completed'); assert.equal(result.batches.batchCount, 2); assert.equal(model.requests.filter((request) => request.operation === 'extractKnowledge').length, 3); assert.equal(result.modelCalls.length, 3); assert.equal(result.modelCalls.reduce((sum, call) => sum + 1 + call.retryCount, 0), 4); assert.equal(changeSet?.ingestionContext && (changeSet.ingestionContext as { modelCalls: number }).modelCalls, 4) } finally { await removeRuntimeKnowledgeBase(root) } })

test('candidate-local rejections do not enter consolidation, reconciliation, ChangeSet, or Writer', async () => { const root = await createV03Root('readonly'); try { const model = new WorkflowModel(); const original = model.invoke.bind(model); model.invoke = async (request) => { const value = await original(request); if (request.operation !== 'extractKnowledge') return value; const extractionValue = value as Record<string, any>; return { ...extractionValue, entities: [...extractionValue.entities, { ...extractionValue.entities[0], name: 'Rejected Entity', evidenceChunkRefs: ['chunk-missing'] }], relations: [extractionValue.relations[0], { ...extractionValue.relations[0], targetMention: { text: 'Company', entityType: 'company', existingRef: null } }, extractionValue.relations[0]], claims: [extractionValue.claims[0], { ...extractionValue.claims[0], statement: 'Rejected claim', semanticConfidence: 2 }] }; }; let changeSet: Record<string, unknown> | undefined; const result = await workflow(root, model, { validation: { validateChangeSet: async (_handle, candidate) => { changeSet = candidate as unknown as Record<string, unknown>; return { report: { status: 'passed', errors: [], warnings: [] } as never } } } }).execute(input('dry_run')); assert.equal(result.status, 'completed'); assert.equal(result.reconciliation.candidates, 0); const extractionCall = result.modelCalls.find((call) => call.operation === 'extractKnowledge')!; assert.deepEqual(extractionCall.candidateValidation?.attempts[0]?.accepted, { entity: 1, relation: 2, claim: 1 }); assert.deepEqual(extractionCall.candidateValidation?.attempts[0]?.rejected, { entity: 1, relation: 1, claim: 1 }); assert.doesNotMatch(JSON.stringify(result.plannedChanges), /Rejected/); assert.doesNotMatch(JSON.stringify(changeSet), /Rejected/); } finally { await removeRuntimeKnowledgeBase(root) } })

test('candidateId injection is a global invalid_reference with one C9 recovery and no leakage', async () => { const root = await createV03Root('readonly'); try { const model = new RetryWorkflowModel().queue('batch-0001', [candidateIdExtraction(), extraction()]); const result = await workflow(root, model).execute(input('dry_run')); const extractionCall = result.modelCalls.find((call) => call.operation === 'extractKnowledge')!; const requests = model.requests.filter((request) => request.operation === 'extractKnowledge'); assert.equal(result.status, 'completed'); assert.equal(requests.length, 2); assert.equal(extractionCall.retryCount, 1); assert.equal(extractionCall.validationFailures?.[0]?.code, 'invalid_reference'); assert.equal(extractionCall.candidateValidation?.attempts.length, 1); assert.deepEqual(extractionCall.candidateValidation?.attempts[0]?.rejected, { entity: 0, relation: 0, claim: 0 }); assert.doesNotMatch(JSON.stringify(extractionCall.candidateValidation), /attacker-candidate-id/); assert.doesNotMatch(extractionCall.validationFailures?.[0]?.message ?? '', /attacker-candidate-id/); assert.doesNotMatch(requests[1]?.instruction ?? '', /attacker-candidate-id/) } finally { await removeRuntimeKnowledgeBase(root) } })

test('persistent candidateId injection blocks after exactly one C9 retry', async () => { const root = await createV03Root('readonly'); try { const model = new RetryWorkflowModel().queue('batch-0001', [candidateIdExtraction(), candidateIdExtraction()]); const result = await workflow(root, model).execute(input('dry_run')); const extractionCall = result.modelCalls.find((call) => call.operation === 'extractKnowledge')!; assert.equal(result.status, 'blocked'); assert.equal(result.errors[0]?.code, 'invalid_reference'); assert.equal(model.requests.filter((request) => request.operation === 'extractKnowledge').length, 2); assert.equal(extractionCall.retryCount, 1); assert.equal(extractionCall.validationFailures?.length, 2); assert.equal(extractionCall.candidateValidation, undefined) } finally { await removeRuntimeKnowledgeBase(root) } })
