import type { WorkflowDefinition } from '../types.ts'

const stages = [
  ['intake-execution-identity', 'Intake / Execution Identity'],
  ['resolve-knowledge-base', 'Resolve Research Knowledge Base'],
  ['document-resolution', 'Document Resolution'],
  ['raw-identity-archive', 'Raw Identity / Raw Archive'],
  ['report-understanding', 'Report Understanding'],
  ['theme-handling', 'Theme Handling'],
  ['broad-context-retrieval', 'Relevant Knowledge Context Retrieval'],
  ['section-batching', 'Section Batching'],
  ['batched-knowledge-extraction', 'Schema-aware Batched Knowledge Extraction'],
  ['candidate-consolidation', 'Candidate Consolidation'],
  ['reference-resolution', 'Deterministic Reference Resolution'],
  ['precise-knowledge-retrieval', 'Existing Knowledge Retrieval'],
  ['batched-reconciliation', 'Batched Knowledge Reconciliation'],
  ['conditional-schema-gaps', 'Conditional Schema Gap Analysis'],
  ['review-isolation-changeset-planning', 'Review Isolation / ChangeSet Planning'],
  ['deterministic-final-validation', 'Deterministic Final Validation'],
  ['atomic-semantic-write', 'Atomic Semantic Write'],
  ['final-result-log-refresh', 'Final Result / Ingestion Log / Projection Refresh'],
] as const

export const researchReportKnowledgeIngestionWorkflowDefinition: WorkflowDefinition = {
  id: 'research-report-knowledge-ingestion',
  name: 'Research Report Knowledge Ingestion',
  description: 'Understand, extract, reconcile, validate, and optionally commit a research report into an explicit Schema 0.3 Knowledge Base.',
  version: '0.3',
  purpose: 'Provide deterministic Workflow composition over document resolution, Raw identity, Knowledge Curation v0.3, native Access, C3 Validation, and atomic Writer.',
  inputSchema: {
    workflowRunId: { type: 'string', required: true, description: 'Path-safe Workflow run identifier.' },
    knowledgeBaseId: { type: 'string', required: true, description: 'Explicit Schema 0.3 target Knowledge Base identifier.' },
    report: { type: 'object', required: true, description: 'Research report input reference and supplied metadata.' },
    options: { type: 'object', required: true, description: 'Commit/dry-run and reprocess controls.' },
  },
  outputSchema: {
    status: { type: 'string', required: true, description: 'completed, completed_with_review, or blocked.' },
    ingestionIdentity: { type: 'string', required: true, description: 'Deterministic logical ingestion identity.' },
    raw: { type: 'object', required: true, description: 'Raw identity and persistence summary.' },
    source: { type: 'object', required: false, description: 'Deterministic Source proposal and resolution.' },
    reportUnderstanding: { type: 'object', required: false, description: 'Structured report understanding.' },
    batches: { type: 'object', required: true, description: 'Deterministic section/batch summary.' },
    extraction: { type: 'object', required: true, description: 'Entity/Relation/Claim extraction counts.' },
    referenceResolution: { type: 'object', required: true, description: 'Four deterministic reference-resolution outcome counts.' },
    reconciliation: { type: 'object', required: true, description: 'Batched reconciliation decisions and classifications.' },
    plannedChanges: { type: 'object', required: true, description: 'Planned v0.3 ChangeSet operations.' },
    committedChanges: { type: 'object', required: true, description: 'Committed operation counts.' },
    validation: { type: 'object', required: false, description: 'C3 validation report.' },
    modelCalls: { type: 'array', required: true, description: 'Observable Curation call accounting.' },
  },
  steps: stages.map(([id, name], index) => ({ id, kind: index < 4 ? 'infrastructure' as const : index >= 14 ? 'workflow' as const : 'skill' as const, ...(index < 4 || index >= 14 ? { component: name } : { skill: index === 6 || index === 11 ? 'knowledge-access' : 'knowledge-curation' }), inputs: [], outputs: [], dependsOn: index === 0 ? [] : [stages[index - 1]![0]] })),
}
