import type { ValuationBasis, ValuationComputation, ValuationMethod, ValuationMethodEligibility, ValuationScenarioAssumption, ValuationScenarioId, ValuationScenarioResult, ValuationSensitivityCell } from './contracts.ts'

const METHOD_SET = new Set<ValuationMethod>(['PE', 'PB', 'EV_EBITDA'])
const SCENARIOS: readonly ValuationScenarioId[] = ['bear', 'base', 'bull']

export interface ValuationMarketObservation { readonly priceDate: string; readonly close: number }
export interface ValuationFinancialRow { readonly basisFiscalYear: number; readonly reportDate: string; readonly publicationDate?: string; readonly aggregatorNoticeDate?: string; readonly eps?: number; readonly bvps?: number; readonly ebitda?: number; readonly netDebt?: number; readonly shares?: number }

export function selectValuationBasis(rows: readonly ValuationFinancialRow[], valuationDate: string, asOf?: string): { readonly basis?: ValuationFinancialRow; readonly publicationStatus?: ValuationBasis['publicationStatus']; readonly pointInTimeVerified: boolean; readonly diagnostics: readonly string[] } {
  const diagnostics: string[] = []; const historical = asOf !== undefined; const valuationCutoff = valuationDate.slice(0, 10); const publicationCutoff = asOf ?? valuationCutoff; const datedRows = rows.filter((row) => row.reportDate <= valuationCutoff); const eligible = datedRows.filter((row) => { if (row.publicationDate === undefined) return !historical; return row.publicationDate <= publicationCutoff });
  if (datedRows.some((row) => row.publicationDate === undefined || row.publicationDate > publicationCutoff)) diagnostics.push('POINT_IN_TIME_PUBLICATION_UNVERIFIED')
  const basis = eligible[0]
  if (basis === undefined) { if (diagnostics.length === 0) diagnostics.push('POINT_IN_TIME_PUBLICATION_UNVERIFIED'); return { pointInTimeVerified: false, diagnostics } }
  return { basis, publicationStatus: historical ? 'verified' : basis.publicationDate === undefined ? 'current_snapshot_unverified' : 'verified', pointInTimeVerified: basis.publicationDate !== undefined && basis.publicationDate <= publicationCutoff, diagnostics }
}

export function buildValuationBasis(market: ValuationMarketObservation, financial: ValuationFinancialRow, valuationDate: string, publicationStatus: ValuationBasis['publicationStatus']): ValuationBasis {
  return { valuationDate, priceDate: market.priceDate, marketPrice: market.close, marketPriceUnit: 'CNY/share', basisFiscalYear: financial.basisFiscalYear, reportDate: financial.reportDate, publicationStatus, ...(financial.eps === undefined ? {} : { eps: financial.eps }), ...(financial.bvps === undefined ? {} : { bvps: financial.bvps }), ...(financial.ebitda === undefined ? {} : { ebitda: financial.ebitda }), ...(financial.netDebt === undefined ? {} : { netDebt: financial.netDebt }), ...(financial.shares === undefined ? {} : { shares: financial.shares }), units: { marketPrice: 'CNY/share', eps: 'CNY/share', bvps: 'CNY/share', ebitda: 'CNY', netDebt: 'CNY', shares: 'shares' } }
}

export function methodEligibility(basis: ValuationBasis): readonly ValuationMethodEligibility[] {
  return [
    { method: 'PE', eligible: basis.marketPrice > 0 && basis.eps !== undefined && Number.isFinite(basis.eps) && basis.eps > 0, reason: basis.eps !== undefined && basis.eps > 0 ? 'positive FY EPS' : 'FY EPS is unavailable or non-positive' },
    { method: 'PB', eligible: basis.marketPrice > 0 && basis.bvps !== undefined && Number.isFinite(basis.bvps) && basis.bvps > 0, reason: basis.bvps !== undefined && basis.bvps > 0 ? 'positive FY BVPS' : 'FY BVPS is unavailable or non-positive' },
    { method: 'EV_EBITDA', eligible: basis.marketPrice > 0 && basis.ebitda !== undefined && Number.isFinite(basis.ebitda) && basis.ebitda > 0 && basis.shares !== undefined && Number.isFinite(basis.shares) && basis.shares > 0 && basis.netDebt !== undefined && Number.isFinite(basis.netDebt), reason: basis.ebitda !== undefined && basis.ebitda > 0 && basis.shares !== undefined && basis.shares > 0 && basis.netDebt !== undefined && Number.isFinite(basis.netDebt) ? 'positive EBITDA with finite net debt and shares' : 'EBITDA, net debt, or shares are unavailable or invalid' },
  ]
}

export function referenceMultiples(basis: ValuationBasis): Readonly<Partial<Record<ValuationMethod, number>>> {
  const result: Partial<Record<ValuationMethod, number>> = {}; if (basis.eps !== undefined && basis.eps > 0) result.PE = basis.marketPrice / basis.eps; if (basis.bvps !== undefined && basis.bvps > 0) result.PB = basis.marketPrice / basis.bvps; if (basis.ebitda !== undefined && basis.ebitda > 0 && basis.netDebt !== undefined && Number.isFinite(basis.netDebt) && basis.shares !== undefined && basis.shares > 0) result.EV_EBITDA = (basis.marketPrice * basis.shares + basis.netDebt) / basis.ebitda; return Object.fromEntries(Object.entries(result).filter(([, value]) => Number.isFinite(value))) as Readonly<Partial<Record<ValuationMethod, number>>>
}

function numeric(value: number, label: string): number { if (!Number.isFinite(value)) throw new TypeError(`${label} is unavailable`); return value }
export function calculateTargetPrice(basis: ValuationBasis, method: ValuationMethod, targetFiscalYear: number, growthRate: number, targetMultiple: number): { readonly forecastMetric: number; readonly targetPrice: number; readonly impliedReturnPct: number } {
  if (!METHOD_SET.has(method) || !Number.isFinite(growthRate) || growthRate <= -1 || !Number.isFinite(targetMultiple) || targetMultiple <= 0 || !Number.isInteger(targetFiscalYear) || targetFiscalYear <= basis.basisFiscalYear) throw new TypeError('Invalid valuation calculation inputs')
  const periods = targetFiscalYear - basis.basisFiscalYear
  if (method === 'PE') { const forecastMetric = numeric(basis.eps ?? Number.NaN, 'EPS') * Math.pow(1 + growthRate, periods); const targetPrice = forecastMetric * targetMultiple; return { forecastMetric: numeric(forecastMetric, 'forecast EPS'), targetPrice: numeric(targetPrice, 'target price'), impliedReturnPct: numeric((targetPrice / basis.marketPrice - 1) * 100, 'implied return') } }
  if (method === 'PB') { const forecastMetric = numeric(basis.bvps ?? Number.NaN, 'BVPS') * Math.pow(1 + growthRate, periods); const targetPrice = forecastMetric * targetMultiple; return { forecastMetric: numeric(forecastMetric, 'forecast BVPS'), targetPrice: numeric(targetPrice, 'target price'), impliedReturnPct: numeric((targetPrice / basis.marketPrice - 1) * 100, 'implied return') } }
  const forecastMetric = numeric(basis.ebitda ?? Number.NaN, 'EBITDA') * Math.pow(1 + growthRate, periods); const targetEV = forecastMetric * targetMultiple; const targetPrice = (targetEV - numeric(basis.netDebt ?? Number.NaN, 'net debt')) / numeric(basis.shares ?? Number.NaN, 'shares'); return { forecastMetric: numeric(forecastMetric, 'forecast EBITDA'), targetPrice: numeric(targetPrice, 'target price'), impliedReturnPct: numeric((targetPrice / basis.marketPrice - 1) * 100, 'implied return') }
}

export function validateScenarioAssumptions(plan: { readonly primaryMethod: ValuationMethod; readonly targetFiscalYear: number; readonly scenarios: readonly ValuationScenarioAssumption[] }, eligibleMethods: readonly ValuationMethod[], basisFiscalYear: number): readonly string[] {
  const errors: string[] = []; if (!eligibleMethods.includes(plan.primaryMethod)) errors.push('primary method is not eligible'); if (plan.targetFiscalYear <= basisFiscalYear || plan.targetFiscalYear > basisFiscalYear + 3) errors.push('target fiscal year is outside the allowed horizon'); if (plan.scenarios.length !== 3 || new Set(plan.scenarios.map((item) => item.scenarioId)).size !== 3 || !SCENARIOS.every((id) => plan.scenarios.some((item) => item.scenarioId === id))) errors.push('exactly Bear/Base/Bull scenarios are required'); const ordered = SCENARIOS.map((id) => plan.scenarios.find((item) => item.scenarioId === id)).filter((item): item is ValuationScenarioAssumption => item !== undefined); for (const item of ordered) { if (item.primaryMethod !== plan.primaryMethod) errors.push(`${item.scenarioId} method mismatch`); if (item.targetFiscalYear !== plan.targetFiscalYear) errors.push(`${item.scenarioId} target fiscal year mismatch`); if (!Number.isFinite(item.growthRate) || item.growthRate <= -1) errors.push(`${item.scenarioId} growthRate invalid`); if (!Number.isFinite(item.targetMultiple) || item.targetMultiple <= 0) errors.push(`${item.scenarioId} targetMultiple invalid`); if (!item.rationale.trim()) errors.push(`${item.scenarioId} rationale missing`) } if (ordered.length === 3 && (ordered[0]!.growthRate > ordered[1]!.growthRate || ordered[1]!.growthRate > ordered[2]!.growthRate || ordered[0]!.targetMultiple > ordered[1]!.targetMultiple || ordered[1]!.targetMultiple > ordered[2]!.targetMultiple)) errors.push('scenario assumptions are not monotonic'); return errors
}

export function calculateValuation(basis: ValuationBasis, plan: { readonly primaryMethod: ValuationMethod; readonly secondaryMethods: readonly ValuationMethod[]; readonly targetFiscalYear: number; readonly scenarios: readonly ValuationScenarioAssumption[] }, eligibleMethods: readonly ValuationMethod[]): ValuationComputation {
  const errors = validateScenarioAssumptions(plan, eligibleMethods, basis.basisFiscalYear); if (errors.length) throw new TypeError(errors.join('; ')); const eligibility = methodEligibility(basis); const reference = referenceMultiples(basis); const scenarios: ValuationScenarioResult[] = SCENARIOS.map((id) => { const assumption = plan.scenarios.find((item) => item.scenarioId === id)!; return { scenarioId: id, primaryMethod: plan.primaryMethod, targetFiscalYear: plan.targetFiscalYear, growthRate: assumption.growthRate, targetMultiple: assumption.targetMultiple, ...calculateTargetPrice(basis, plan.primaryMethod, plan.targetFiscalYear, assumption.growthRate, assumption.targetMultiple) } }); if (scenarios[0]!.targetPrice > scenarios[1]!.targetPrice || scenarios[1]!.targetPrice > scenarios[2]!.targetPrice) throw new TypeError('scenario target prices are not monotonic'); const sensitivity: ValuationSensitivityCell[] = []; for (const growth of SCENARIOS) for (const multiple of SCENARIOS) { const growthAssumption = plan.scenarios.find((item) => item.scenarioId === growth)!; const multipleAssumption = plan.scenarios.find((item) => item.scenarioId === multiple)!; sensitivity.push({ cellId: `sensitivity-${growth}-${multiple}`, growthScenario: growth, multipleScenario: multiple, growthRate: growthAssumption.growthRate, targetMultiple: multipleAssumption.targetMultiple, targetPrice: calculateTargetPrice(basis, plan.primaryMethod, plan.targetFiscalYear, growthAssumption.growthRate, multipleAssumption.targetMultiple).targetPrice }) } const recomputed = scenarios.map((item) => calculateTargetPrice(basis, item.primaryMethod, item.targetFiscalYear, item.growthRate, item.targetMultiple).targetPrice); const deterministicRecomputeMatched = recomputed.every((value, index) => value === scenarios[index]!.targetPrice) && sensitivity.length === 9 && sensitivity.every((cell) => Number.isFinite(cell.targetPrice)); return { basis, eligibility, referenceMultiples: reference, scenarios, sensitivity, deterministicRecomputeMatched, unavailable: [] }
}
